apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-ebs-pvc-2
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: test-ebs-sc-2