apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-ebs-pv-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-0d3fdc69863e01360
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: test-ebs-sc