apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-ebs-sc-2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-central-1a
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
